import type { AlgorithmSection } from "./types";

const ollSections: AlgorithmSection[] = [
  {
    id: "oll-edge-orientation",
    title: "OLL Edge Orientation",
    description: "Orient the last-layer edges to form the OLL cross.",
    cases: [
      {
        id: "oll-edge-line",
        name: "Line Case",
        algorithm: "F (R U R' U') F'",
        note: "Hold the line horizontally.",
        diagram: {
          stickers: [
            "empty",
            "empty",
            "empty",
            "accent",
            "accent",
            "accent",
            "empty",
            "empty",
            "empty",
          ],
        },
      },
      {
        id: "oll-edge-l-shape",
        name: "L Case",
        algorithm: "f (R U R' U') f'",
        note: "Place the L in the upper-right corner.",
        diagram: {
          stickers: [
            "empty",
            "empty",
            "empty",
            "empty",
            "accent",
            "accent",
            "empty",
            "accent",
            "empty",
          ],
        },
      },
      {
        id: "oll-edge-dot",
        name: "Dot Case",
        algorithm: "F (R U R' U') F' f (R U R' U') f'",
        note: "Reduce to the line or L case, then complete edge orientation.",
        diagram: {
          stickers: [
            "empty",
            "empty",
            "empty",
            "empty",
            "accent",
            "empty",
            "empty",
            "empty",
            "empty",
          ],
        },
      },
    ],
  },
  {
    id: "oll-corner-orientation",
    title: "OLL Corner Orientation",
    description: "Orient the last-layer corners after edge orientation.",
    cases: [
      {
        id: "oll-corner-sune",
        name: "Sune Case",
        algorithm: "R' U2 R U R' U R",
        note: "Hold the case as shown before executing.",
        diagram: {
          sideStickers: [
            { side: "top", index: 0 },
            { side: "right", index: 0 },
            { side: "left", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "empty",
            "filled",
            "filled",
            "filled",
            "empty",
            "filled",
            "filled",
          ],
        },
      },
      {
        id: "oll-corner-anti-sune",
        name: "Anti-Sune Case",
        algorithm: "R U' U' R' U' R U' R'",
        note: "The mirror case of Sune. Hold the case as shown before executing.",
        diagram: {
          sideStickers: [
            { side: "left", index: 0 },
            { side: "bottom", index: 0 },
            { side: "right", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "empty",
            "filled",
            "empty",
          ],
        },
      },
      {
        id: "oll-corner-chameleon",
        name: "Chameleon Case",
        algorithm: "(r U R' U') (r' F R F')",
        note: "Place the two matching side-facing corners on the left.",
        diagram: {
          sideStickers: [
            { side: "top", index: 0 },
            { side: "bottom", index: 0 },
          ],
          stickers: [
            "empty",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "empty",
            "filled",
            "filled",
          ],
        },
      },
      {
        id: "oll-corner-bowtie",
        name: "Bowtie Case",
        algorithm: "F'(r U R' U') (r' F R)",
        note: "Use when two diagonal last-layer corners are unoriented.",
        diagram: {
          sideStickers: [
            { side: "left", index: 0 },
            { side: "bottom", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "empty",
          ],
        },
      },
      {
        id: "oll-corner-headlights",
        name: "Headlights Case",
        algorithm: "(R2 D') (R U'U') (R' D) (R U'U' R)",
        note: "Use when the two unoriented corners occupy the same row.",
        diagram: {
          sideStickers: [
            { side: "top", index: 0 },
            { side: "top", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "empty",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
            "filled",
          ],
        },
      },
      {
        id: "oll-corner-h",
        name: "H Case",
        algorithm: "(R U U R' U') (R U R' U') (R U' R')",
        note: "The two side sticker pairs face opposite sides.",
        diagram: {
          sideStickers: [
            { side: "top", index: 0 },
            { side: "top", index: 2 },
            { side: "bottom", index: 0 },
            { side: "bottom", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "empty",
            "filled",
            "filled",
            "filled",
            "empty",
            "filled",
            "empty",
          ],
        },
      },
      {
        id: "oll-corner-pi",
        name: "Pi Case",
        algorithm: "R U'U' (R2' U') (R2 U') R2' U2 R",
        note: "Use when the side sticker pairs sit on the same side.",
        diagram: {
          sideStickers: [
            { side: "left", index: 0 },
            { side: "left", index: 2 },
            { side: "top", index: 2 },
            { side: "bottom", index: 2 },
          ],
          stickers: [
            "empty",
            "filled",
            "empty",
            "filled",
            "filled",
            "filled",
            "empty",
            "filled",
            "empty",
          ],
        },
      },
    ],
  },
];

export default ollSections;
